version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: marketplace
    ports:
      - "5432:5432"

  data_writer:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres